image:
  file: devcontainer/.gitpod.Dockerfile

tasks:
  - name: Install Packages
    before: sudo apt-get install qemu-system -y && sudo apt-get install p7zip-full -y && curl -fsSL https://tailscale.com/install.sh | sh
  - name: On Create
    init: sudo bash devcontainer/onCreateCommand.sh
  - name: Post Start
    command: sudo bash devcontainer/postStartCommand.sh
  - name: Post Attach
    command: sudo bash devcontainer/postAttachCommand.sh

ports:
  - port: 22
    name: GitHub Codespaces (SSH)
    onOpen: notify
  - port: 3389
    name: QEMU (RDP)
    onOpen: notify
  - port: 5900
    name: QEMU (VNC)
    onOpen: notify
  - port: 8006
    name: QEMU (HTTP/HTTPS)
    onOpen: notify
# Note: Gitpod does not support all Docker run options (like privileged, capAdd, securityOpt, or custom device mounts).
# These options are omitted or may require Gitpod workspace configuration or custom workspace images.
# Workspace folder is set automatically in Gitpod.
